### PR TITLE
Add Owns() for generated resources. Document major TODOs

### PR DESCRIPTION
**Pull request by empovit**

### CODE REVIEW

**Comment by mresvanis** [comment]
@empovit you can run locally `make lint` to verify that linting is successful. Currently, it fails with the following error:

```shell
level=info msg="[runner/max_same_issues] 6/9 issues with text \"Error return value is not checked\" were hidden, use --max-same-issues"
Error: controllers/fdoonboardingserver_controller.go:343:30: Error return value is not checked (errcheck)
level=info msg="[runner] Issues before processing: 12, after processing: 6"
level=info msg="[runner] Processors filtering stat (out/in): path_prettifier: 12/12, identifier_marker: 12/12, diff: 12/12, max_from_linter: 6/6, sort_results: 6/6, filename_unadjuster: 12/12, skip_dirs: 12/12, nolint: 12/12, source_code: 6/6, severity-rules: 6/6, path_prefixer: 6/6, cgo: 12/12, skip_files: 12/12, exclude-rules: 12/12, uniq_by_line: 12/12, max_per_file_from_linter: 12/12, max_same_issues: 6/12, path_shortener: 6/6, autogenerated_exclude: 12/12, exclude: 12/12"
level=info msg="[runner] processing took 2.4709ms with stages: nolint: 1.509ms, path_prettifier: 361.8µs, exclude-rules: 240.3µs, identifier_marker: 146.5µs, autogenerated_exclude: 92.7µs, source_code: 54µs, max_same_issues: 25.8µs, skip_dirs: 25.1µs, uniq_by_line: 4.3µs, path_shortener: 3µs, cgo: 2.3µs, max_from_linter: 2.1µs, filename_unadjuster: 1.2µs, max_per_file_from_linter: 1µs, severity-rules: 400ns, skip_files: 400ns, diff: 300ns, exclude: 300ns, sort_results: 200ns, path_prefixer: 200ns"
level=info msg="[runner] linters took 28.070364453s with stages: goanalysis_metalinter: 28.067818053s"
level=info msg="File cache stats: 2 entries of total size 26.3KiB"
level=info msg="Memory: 833 samples, avg is 278.5MB, max is 1037.0MB"
level=info msg="Execution took 1m23.193154018s"
		ctrl.SetControllerReference(server, deploy, r.GetScheme())
```

**Comment by empovit** [comment]
@mresvanis the linter violations were fixed by #13, I just didn't want to push too many unrelated changes in one PR

**Comment by mresvanis** [comment]
> @mresvanis the linter violations were fixed by #13 ([example](https://github.com/empovit/fdo-operator/pull/13/files#diff-b62827b248ade8b98161b308a5baf75b2ac1acbe89158ff336887518ff3de8e4L338)) I just didn't want to push too many unrelated changes in one PR.

Oh I just saw it, I apologize, we can merge that one first and then rebase the rest. WDYT?

**Comment by empovit** [comment]
@mresvanis done

**Pull request merged**
